# Generated by Django 4.1.7 on 2023-04-02 01:10

import api.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('diretor', models.CharField(max_length=155)),
                ('imagem_filme', models.ImageField(null=True, upload_to=api.models.upload_imagem_filme)),
                ('data_cadastro', models.DateField(auto_now_add=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disponibilidade', models.CharField(choices=[('netflix', 'Netflix'), ('cinema', 'Cinema'), ('hbo', 'HBO'), ('appletv', 'AppleTV'), ('prime_video', 'Prime Vídeo'), ('globoplay', 'Globoplay'), ('disney', 'Disney+'), ('outros', 'Outros')], max_length=25)),
            ],
        ),
    ]
